apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: share-message
spec:
  params:
    - name: message
      type: string
  workspaces:
    - name: pipeline-space
  tasks:
    - name: write
      taskRef:
        name: write-message
      params:
        - name: message
          value: $(params.message)
      workspaces:
        - name: messages
          workspace: pipeline-space
    - name: read
      runAfter:
        - write
      taskRef:
        name: read-message
      workspaces:
        - name: messages
          workspace: pipeline-space
