apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world
spec:
  params:
  - name: message
    type: string
    description: The message you want to say
  steps:
    - name: say-hello
      image: docker/whalesay 
      script: |
        #!/usr/bin/env sh
        cowsay $(params.message)
